# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy to DO

on:
  registry_package:

  workflow_run:
    workflows:
      - "Build image"
    types:
      - completed

jobs:
  deploy-to-do:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Digital Ocean droplet via SSH
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./sc-actions/
            docker-compose stop
            docker pull ghcr.io/smart-chef-dev/sc-actions-client/sc-actions-client:latest
            docker-compose up -d

      - name: Deploy to Digital Ocean develop droplet via SSH
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          password: ${{ secrets.PASSWORD_DEV }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            cd ./sc-actions/
            docker-compose stop
            docker pull ghcr.io/smart-chef-dev/sc-actions-client/sc-actions-client:dev
            docker-compose up -d

